DATABRICKS_SETUP = "databricks_setup"
PRODUCT_SEARCH = "product_search"
SPARK_TABLE_SETUP = "spark_table_setup"
SPARK_PRODUCT_DOWNLOAD_ETL = "spark_daily_product_download_etl"
SPARK_PRODUCT_RECOMMENDATIONS = "spark_product_recommendations"
SPARK_USER_EVENTS = "spark_user_events_stream_v2"
