version: '3'
services:
  test:
    image: rec-model:latest
    volumes:
      - ./input:/opt/ml/processing/input
      - ./processing.py:/processing.py
    command: "/processing.py \
              --main_input_path=/opt/ml/processing/input/user_product_data.jsonl.out \
              --id_input_path=/opt/ml/processing/input/user_ids.jsonl \
              --project=fleek-prod \
              --bq_output_table=fleek-prod.gcs_imports.user_product_recommendations \
              --processor_path=/opt/ml/processing/input/processor.pickle"
